name: Build and Publish

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name to build'     
        required: true
        default: 'master'
      config:
        description: 'Build configuration'     
        required: true
        default: 'Release'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.0.0
      with:
        lfs: 'true'
        ref: '${{ github.event.inputs.branch }}'
    - name: Setup .NET
      uses: actions/setup-dotnet@v2.0.0
      with:
        dotnet-version:  | 
          3.1.x
          6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c ${{ github.event.inputs.config }} --no-restore
    - name: Test
      run: dotnet test -c ${{ github.event.inputs.config }} --no-build --verbosity normal --collect:"XPlat Code Coverage" --settings coverlet.runsettings
    - name: Publish
      run: |
        cd ./src/ \
        && dotnet pack --include-symbols -c ${{ github.event.inputs.config }} -o ./bin/ \
        && cd ./bin/ \
        && dotnet nuget push "*.nupkg" -k ${{ secrets.NuGetApiKey }} -s https://api.nuget.org/v3/index.json
