name: .NET

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name to build'     
        required: true
        default: 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.0.0
      with:
        lfs: 'true'
        ref: '${{ github.event.inputs.branch }}'
    - name: Setup .NET
      uses: actions/setup-dotnet@v2.0.0
      with:
        dotnet-version:  | 
          3.1.x
          6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --settings coverlet.runsettings
